trigger:
- main
- drafts
- draft/*

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'dotnet install'
  inputs:
    packageType: 'sdk' # Options: runtime, sdk
    version: '2.1.500'

- powershell: '.\build.ps1 -t AzureDevOps' 
  displayName: 'cake build'
