# This is a basic workflow to help you get started with Actions

name: Build Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - main
    - drafts
    - draft/*
  pull_request:
    branches: [ main, drafts ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 2.1.500

    - name: Cake Build
      shell: bash
      run: ./build.sh -t GitHubActions
      env:
        NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
