name: publish

on:
  push:
    branches:
      - main
      - draft/*

  pull_request:
    branches:
      - main

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: 'false'
          fetch-depth: '0'
      - name: Nuke
        run: ./build.cmd GitHubActions
        env:
            NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
            NETLIFY_URL: ${{ secrets.NETLIFY_URL }}
